---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: quay-pull-secret
  namespace: clopus-watcher
spec:
  encryptedData:
    .dockerconfigjson: AgA1NFBgqnxDRajT79jlFDNr+KOwHu8DRUduVRWmiw0H+vty8pjUpx1X60vOAulKfj2+eyidtVGQ9vYNgyibhsWBga8xrO6BpkapUbVSUGb4rWiDShWIByTfDlQGPTMH/2hML99oDxRjJAnC2PE36mjXiqAAa+FKGP+nyYR/MBiTWyW6/csIuO8lI+GuGoxS//MvMFr/6XX2UlW09HDCE1+bCYeeOpAnWK2usY39bt0vBY7jYirDz10RxwNM47KaV8N+mlmZtTXPl+lBzZ53PBQr4PPdRAtubuN8zz0l5sosER6jJuxIQWthv1uh/Cym467LwHEFoyKs2VyjWnSXCI9kS0goVkB06Vzi4nG4YicOM33UzdytPXlxazrNVAyYyfRPLZpdEGgRVtld1UN5bLuWKN0RMyTb6jLyEK4KERgq7/ylnbWU1gNcfTkCwhhXZtJ06OJAvr+ZInhDigO2zW1Wdh/PCfyRrVbI9eRoL03P2BVA6xOG6HrUELFWE13chb5z0aUyv5ti3UGhI+/motjX5yBdp+qzEalM1B6VUDyKsfxJl9GgHIn42oT+sjflAjKrnzI/7RpYxfLpFn79AeX8Nr9jCIT7Qs8674e643v+/k8oh5iiFC/P8fIBi9UtVebIRU7ZjDqO8zwMJTtVsm0bjlBIWstuM8Y1bm8JJdID68lFVz4rZ5w27bmbFwBjFFOu4b0oNjyiHFstLFCr2OAs3reC1RIbzMVy+tzi/5ongp3NN9eP/G5ee2aaEYF6yuIXVURThe4OKv/izD+0uAArbxrTFl9P8MspLafOKEiLjOhUGOZaX3U13VIVkOe5
  template:
    metadata:
      name: quay-pull-secret
      namespace: clopus-watcher
    type: kubernetes.io/dockerconfigjson
