---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: claude-auth
  namespace: clopus-watcher
spec:
  encryptedData:
    api-key: AgB6Ci0zap8MXzpRn0NOcqrC++utWNapaU4hCGV5Quz6PE4kyYCWKRVcnwOrTGN3enBCTosPypz2KtOr6A8ybIJ8FJ7qX/RDwotHox9Yzh9ye4l1JDY4i89LLxNfv14RYjjoUSSR/9RGF4KLutvHiBwlF5rQPWr5CJeJMdFJKl2Qf9Y3f/8rYlSqSpoT/9HTNdE2xQzq5CEM13JA6svw0Vxv3dA5j8+Mh83tE34Cj4xpLGQ7xM3rUNWW3/f0USoNUXLvefW5vY5Ki+yCVMVU48txrXxyWOVdSood+AHdDh6dsPZKawW7ljwmdFb25YNB8NlFp24HtekxyRwGRiCHmIdtAWRkWmqg2w7mAFVzQ6w1dr+KByIDq8PvZO6XbRUuoQD0puHcbig33VfkbBuN3x+QhqsxaRjbBoxTYmtDQ9emHRzMh5oYZZuEPW8PUIAs3rtFX1mesqN2edMRbT/HF+1nVgpisH8e1Yy/QAPfmE1A67q5c5egln4w3yrqO+RvXZyoDdRkEiG1zykZpv8pyLBfyrGdNSlj4ogKtvLT9W0MZtBDiKAMklgsME57857dUaQ4d379WCMwfu9KhgKGt39FFDyf79EcRWm5MfAlW2Mhc87PVFGXSaMH8WGSLEoMgEraSpaLvqxC4XZIrhab9lUsuXKB23mgf07i6ypwkYfQ3PMq4GMTI4VhAW8RAZpxai9Sq4A82seGDMdIm3rvxz0SHHodjE37WYJMkrHTCruqM/e1q3GTD8eOnXK1Dq07dHETauAT4xh9pnG8bbhDJoju9MSzNh+ljglZZ5lb2fw8lcJm2mAyxH9dvMXMPSlhTKdSYghmkgbNMDvDMT8=
  template:
    metadata:
      name: claude-auth
      namespace: clopus-watcher
    type: Opaque
