---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: claude-auth
  namespace: clopus-watcher
spec:
  encryptedData:
    api-key: AgCWcQGmxqUFc2O3sdt/fySBMh7H7bK3wc/6pjONqcuBX0QRkJ8sdPcbRj2EUxDFEpMouTD0Q9yMJxnCdP1AUvOaX0EVUIQMk9D0o6ZuxMeoIcM18cPS9WbQ1yerywJYa7BVNzJz30jeeo19TQtC5I7/1iQ4nzgEDYRF/iRi2BheMvGM1yqBrWe9fEoBxVPTNloCM5HsSyIxHFivMYly8iu35x+pmSa+TzPwUIabNywMsNbwJ8sZcZZ6wuw33u60LKlgKV8IOkHtD+njCVPy2IY3gzrBf4wkm8X9TRuseKHlyUHH/vWCBdZcOxG7jNpFMt/szj2AqN766pAME+AkHwoTAoJ52V5qs0Wieau6izfsz/TTc0erJ7nTwgRMCvRB87QSaRKorx6o2DA0p5nJtcdIii5WE3yWSCw4u+AMhzvriCSklgmMVQkIAN0PTsVYY3xz4CcWcBYC5wsOqLIQr0yR+HxtSSQf13pHgDLo1Zpo+ccnCQOwIPOBy88ttbRJb3GhNBFd9FvbpvCgXfpI6NkE/N+m4fylEleJW5fQeZ5uwmzdGyRUty0HKgYaOjyW/+KJreoGjPRFgptN/h98c7itNS1zKlurn29eOY/k6Po9Y8kCRkbnmh+JjmFAcPUmjcNXPu2T1TbX2FntV68El+nduycJD+AFJwxXeXZ14CDJStk724mAlF6aQcyjxW8Zfss/34xC8d691sRy8D/zF9He3twok+Bz7aybo1MPzIHwVrJAw8pSTT4dW+sRYB1WMCrYb0thDIaSWhMH33Sgw2RfV/Ofn8tbsJ9+gUUMVDkyDbOFJWqhbq5Bz5a1QG5P+0OXrkVU3ul5uJZCoIg=
  template:
    metadata:
      name: claude-auth
      namespace: clopus-watcher
    type: Opaque
